### ISSUE TITLE
HDT public tracker not supported

### ISSUE THREAD

**Issue by linlinlin3** [LameLemon/IMDb-Lookup#1]
If a filename includes the ‘HDT’ public tracker string the browser does not open. 
```
python imdb-lookup.py "Maze.Runner.The.Scotch.Trials.2015.1080p.BluRay.H264.AAC-HDT"
```

Without the HDT string the code works as expected and opens a new tab in the browser for Maze Runner.

**Comment by LameLemon** [comment]
This would be an easy fix, if you do not see any keywords being filtered by the script just add it on a newline in the keywords.txt file. In this case you could add "HDT" to that list.
